---
# This role installs HAProxy and configures it.

- name: Download and install haproxy
  yum:
    name: haproxy
    state: present

- name: SELinux permit haproxy to connect
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  when: sestatus
    
- name: Configure the haproxy cnf file with hosts
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes
