---
- name: deply webapp yum repo
  copy:
    src: "{{ webapp }}.repo"
    dest: "/etc/yum.repos.d/{{ webapp }}.repo"

- name: Install webapp package
  yum:
    name: "{{ webapp }}"
    version: "{{ webapp_version }}"
    state: present

